# Generated by Django 4.2.1 on 2023-08-16 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(choices=[('latest', 'Latest Article'), ('updated', 'Updated Article'), ('new', 'New Article'), ('tech', 'Technical Article')], default='latest', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='latestpostform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulatestpost', models.TextField(default='')),
                ('ualatestpost', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='newpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unewpost', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=35)),
                ('upass', models.CharField(max_length=12)),
                ('ugender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEmale')], default='male', max_length=8)),
                ('ucourse', models.CharField(choices=[('java', 'JAVA'), ('python', 'PYTHON')], default='java', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='techpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utechpost', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='updatedpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedpost', models.TextField(default='')),
            ],
        ),
    ]
