# Generated by Django 4.2.1 on 2023-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='ucourse',
            field=models.CharField(choices=[('java', 'JAVA'), ('python', 'PYTHON')], default='java', max_length=50),
        ),
    ]
