# Generated by Django 4.2.1 on 2023-08-17 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0003_sportpostform_delete_updatedpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='internationalpostform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uinternationalpost', models.TextField(default='')),
                ('uainternationalpost', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='technicalpostform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utechnicalpost', models.TextField(default='')),
                ('uatechnicalpost', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='newpost',
        ),
        migrations.DeleteModel(
            name='techpost',
        ),
    ]
