# Generated by Django 4.2.1 on 2023-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0005_latestpostform_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalpostform',
            name='img_url',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sportpostform',
            name='img_url',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='technicalpostform',
            name='img_url',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
