# Generated by Django 4.2.1 on 2023-08-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0007_leftaddform_rightaddform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rightaddform',
            new_name='leftpostform',
        ),
        migrations.RenameModel(
            old_name='leftaddform',
            new_name='rightpostform',
        ),
        migrations.RenameField(
            model_name='leftpostform',
            old_name='uarightadd',
            new_name='ualeftpost',
        ),
        migrations.RenameField(
            model_name='leftpostform',
            old_name='urightadd',
            new_name='uleftpost',
        ),
        migrations.RenameField(
            model_name='rightpostform',
            old_name='ualeftadd',
            new_name='uarightpost',
        ),
        migrations.RenameField(
            model_name='rightpostform',
            old_name='uleftadd',
            new_name='urightpost',
        ),
    ]
