# Generated by Django 4.2.1 on 2023-09-06 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0009_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='astrologypostform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uastrologypost', models.TextField(default='')),
                ('uaastrologypost', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_url', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
