# Generated by Django 4.2.1 on 2023-09-07 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0010_astrologypostform_delete_pdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifestylepostform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulifestylepost', models.TextField(default='')),
                ('ualifestylepost', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_url', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
