# Generated by Django 4.2.1 on 2023-09-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0012_pdffile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
