# Generated by Django 4.2.1 on 2023-09-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anand', '0014_pdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='ucourse',
            field=models.CharField(choices=[('java', 'JAVA'), ('python', 'PYTHON')], default='Aadhar Card', max_length=50),
        ),
    ]
